# Generated by Django 4.0.4 on 2022-05-17 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=120, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=120, verbose_name='Фамилия')),
                ('contry', models.CharField(max_length=120, verbose_name='Гражданство')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='Название издательства')),
                ('city', models.CharField(max_length=60, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('status', models.CharField(blank=True, choices=[('r1', 'Роман'), ('p', 'Поэма'), ('s', 'Стихотворение'), ('r2', 'Рассказ')], default='r1', max_length=2, verbose_name='Жaнр')),
                ('sheets', models.IntegerField(verbose_name='Кол-во страниц')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Books.author', verbose_name='Автор')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Books.publisher', verbose_name='Издатель')),
            ],
        ),
    ]
